// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVBzxbJxa2YbaZ5k5HGPKyjKUAC75jqd0',
    appId: '1:693891406723:web:102ae135b1c82d6d3c34b6',
    messagingSenderId: '693891406723',
    projectId: 'bodytech-test',
    authDomain: 'bodytech-test.firebaseapp.com',
    storageBucket: 'bodytech-test.firebasestorage.app',
    measurementId: 'G-7EZHYMLYS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVLNqbaaGPAfCfdx4tk3KUP9-Ik9T2fgU',
    appId: '1:693891406723:android:9e010d2223cbb10e3c34b6',
    messagingSenderId: '693891406723',
    projectId: 'bodytech-test',
    storageBucket: 'bodytech-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADWiNB9YqGt5mMcAxD3jjpwATFkG4YwPk',
    appId: '1:693891406723:ios:2440c29ada70dcc13c34b6',
    messagingSenderId: '693891406723',
    projectId: 'bodytech-test',
    storageBucket: 'bodytech-test.firebasestorage.app',
    iosBundleId: 'com.bodytech.prueba.bodytechTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADWiNB9YqGt5mMcAxD3jjpwATFkG4YwPk',
    appId: '1:693891406723:ios:2440c29ada70dcc13c34b6',
    messagingSenderId: '693891406723',
    projectId: 'bodytech-test',
    storageBucket: 'bodytech-test.firebasestorage.app',
    iosBundleId: 'com.bodytech.prueba.bodytechTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVBzxbJxa2YbaZ5k5HGPKyjKUAC75jqd0',
    appId: '1:693891406723:web:530cd9579c154c273c34b6',
    messagingSenderId: '693891406723',
    projectId: 'bodytech-test',
    authDomain: 'bodytech-test.firebaseapp.com',
    storageBucket: 'bodytech-test.firebasestorage.app',
    measurementId: 'G-Q8EF2K0SXS',
  );
}
